import React, { useState } from "react";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "~/components/ui/card";
import { Label } from "~/components/ui/label";
import { Input } from "~/components/ui/input";

import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { Button } from "~/components/ui/button";

import { api } from "~/utils/api";
import { LoginRegisterData } from "~/utils/types";

export default function Home() {
  const [formMode, setFormMode] = useState("signup");
  const [formData, setFormData] = useState<LoginRegisterData>({
    name: "",
    username: "",
    email: "",
    password: "",
  });

  const signupMutation = api.user.register.useMutation();
  const loginMutation = api.user.login.useMutation();

  const handleSubmit = async (event: React.FormEvent) => {
    event.preventDefault();
    console.log(formData);

    try {
      if (formMode === "signup") {
        const response = await signupMutation.mutateAsync(formData);
        console.log("Signup successful", response);
      } else {
        const response = await loginMutation.mutateAsync(formData);
        console.log("Login successful", response);
      }
    } catch (error) {
      console.error("Error:", error);
    }
  };

  return (
    <>
      <Head>
        <title>Project Management App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen w-full items-center justify-center bg-gray-100 px-4 py-12 dark:bg-gray-950">
        <div className="w-full max-w-md space-y-4">
          <Card>
            <CardHeader className="space-y-1">
              <CardTitle className="text-2xl font-bold">
                {formMode === "login" ? "Login" : "Sign Up"}
              </CardTitle>
              <CardDescription>
                {formMode === "login"
                  ? "Enter your email and password to access your account."
                  : "Enter your email and create a new password."}
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <form onSubmit={handleSubmit}>
                {/* name */}
                {formMode === "signup" && (
                  <div className="space-y-2">
                    <Label htmlFor="name">Full Name</Label>
                    <Input
                      id="name"
                      type="text"
                      placeholder="Gaurav Sharma"
                      required
                      onChange={(e) =>
                        setFormData({ ...formData, name: e.target.value })
                      }
                    />
                  </div>
                )}

                {/* username */}
                {formMode === "signup" && (
                  <div className="space-y-2">
                    <Label htmlFor="username">UserName</Label>
                    <Input
                      id="username"
                      type="text"
                      placeholder="fantasyinfo"
                      required
                      onChange={(e) =>
                        setFormData({ ...formData, username: e.target.value })
                      }
                    />
                  </div>
                )}

                {/* email */}
                <div className="space-y-2">
                  <Label htmlFor="email">Email</Label>
                  <Input
                    id="email"
                    type="email"
                    placeholder="m@example.com"
                    required
                    onChange={(e) =>
                      setFormData({ ...formData, email: e.target.value })
                    }
                  />
                </div>

                {/* password */}
                <div className="space-y-2">
                  <Label htmlFor="password">Password</Label>

                  <Input
                    id="password"
                    type="password"
                    required
                    onChange={(e) =>
                      setFormData({ ...formData, password: e.target.value })
                    }
                  />
                </div>
                <Button type="submit" className="mt-3 w-full">
                  {formMode === "login" ? "Login" : "Sign Up"}
                </Button>
              </form>
            </CardContent>
            <CardFooter className="text-center text-sm">
              {formMode === "login" ? (
                <>
                  Don't have an account?{" "}
                  <Button
                    variant="link"
                    onClick={() => setFormMode("signup")}
                    className="font-medium text-gray-500 underline underline-offset-2 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                  >
                    Sign up
                  </Button>
                </>
              ) : (
                <>
                  Already have an account?{" "}
                  <Button
                    variant="link"
                    onClick={() => setFormMode("login")}
                    className="font-medium text-gray-500 underline underline-offset-2 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                  >
                    Login
                  </Button>
                </>
              )}
            </CardFooter>
          </Card>
        </div>
      </main>
    </>
  );
}
